### ISSUE TITLE
yooo im grounded 

### ISSUE THREAD

**Issue by endr1337** [SuperPixieDust/superpixiedust#3]
so like no messages :)

**Comment by SuperPixieDust** [comment]
> so like no messages :)

BRUH OMG

**Comment by endr1337** [comment]
other than like github ig lmao uhhh i dont know when i can be ungrounded can you send me some links at my email: endertermd1337

**Comment by SuperPixieDust** [comment]
> other than like github ig lmao uhhh i dont know when i can be ungrounded can you send me some links at my email: endertermd1337 

ite, I emailed you.
